FROM node:16-alpine3.18 as BASE
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build


FROM node:16-alpine3.18
WORKDIR /app
COPY --from=BASE /app/dist ./dist
COPY --from=BASE /app/package.json ./package.json
COPY --from=BASE /app/package-lock.json ./package-lock.json
RUN npm i --omit=dev
EXPOSE 3000
CMD npm run start