name: "Bump version"

on:
  push:
    branches:
      - alpha
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3.7.12
        with:
          release-type: node
          package-name: server
        